### PR TITLE
Suggested changes for pimatic 0.9 readiness

### PR DESCRIPTION
**Pull request by mwittig**
A couple of changes are required to run your plugin with the upcoming pimatic 0.9 release. All changes done _should be backwards compatible_. However, _please test thoroughly_ with your setup as I don't have the hardware in place. I have also extended the device config schema to improve the user experience with the new device editor provided with pimatic 0.9

### CODE REVIEW

**Comment by skarcha** [comment]
Hey! Thank you very much Marcus! I'll test it ASAP.

**Comment by skarcha** [comment]
Works great @mwittig !

Only one warning:

`19:55:25.306 [pimatic] The device type NutSensor does not implement a destroy function`

Could you please help me with that too? Thanks!

**Comment by skarcha** [comment]
I've just added this:

``` CoffeeScript
destroy: ->
  @destroy()
  super()
```

And the warning disappears... Is this enough?

**Comment by mwittig** [comment]
Hi. You only need to add a destroy method to the device class, i.e. NutSensor. For this you don't need the statement  @destroy(). What you need to, however, is to cancel the interval timers! See the following PR, for example (I haven't tested the code, but it should work).
Pull Request: https://github.com/skarcha/pimatic-nut/pull/2
Diff: https://github.com/skarcha/pimatic-nut/pull/2/commits/26bb8b3828ccdddc8598f4368e3102a63182287a

**Comment by skarcha** [comment]
Great! Thank you @mwittig !

**Pull request merged**
